### ISSUE TITLE
welcome!

### ISSUE THREAD

**Issue by cooler-SAI** [JadeEmu/JadeCore_547#1]
I welcome all new and old team members - let's Rock this world!!!

**Comment by Mysterium** [comment]
thanks, i hope i have now more time and should i set up a forum for this project on my server? i don't use the server, so i can set up a hp or forum

**Comment by cooler-SAI** [comment]
we need to discuss it - but good idea I think

**Comment by cybrann** [comment]
Damn need to clone new repository... and I just got used to the last one

**Comment by cybrann** [comment]
Btw guys I will create new labels that are similar to trinity core for easier bug tracking and pull request tracking

**Comment by cooler-SAI** [comment]
@cybrann ok, good idea )))

**Comment by Bodeguero** [comment]
@cybrann I can do this if you have as an organization administrator!

**Comment by cybrann** [comment]
Check new labels, I hope you like them :D

**Comment by alexkulya** [comment]
WOW. Unexpectedly.

**Comment by cooler-SAI** [comment]
good!))))

**Comment by alexkulya** [comment]
I tried implement mmap system, compilation without errors (fix), worldserver.conf support, loaded at start server, but in game 0 changes. Bad!

**Comment by cooler-SAI** [comment]
@alexkulya , mmaps is our one of few main targets, It's good to know that someone work on it )

**Comment by Mysterium** [comment]
I have set up a forum: https://jadecore.tk/
You can use it, if you want..

**Comment by cybrann** [comment]
I suppose we don't need this anymore so I'll close
