### ISSUE TITLE
Logging in to game server

### ISSUE THREAD

**Issue by darkmord1991** [JadeEmu/JadeCore_547#10]
Hello,

I think my server is configured right. 
I used fresh DB from your source and the newest core, which I compiled.
But I am not able to login.
I just keep hanging around on the realm screen and if I click on the realm, there just pops up logging in to game server and nothing happens.
There is no output in the console.

Please help me.

**Comment by Bodeguero** [comment]
@darkmord1991 the realm was added correctly? You put the correct IP to connect? The ports were released / open on your firewall?

**Comment by darkmord1991** [comment]
Yes everything seems alright.
Its configured the same way as my working WOTLK TC server.

**Comment by darkmord1991** [comment]
You may wanna take a look via Teamviewer or so?

**Comment by cooler-SAI** [comment]
you must use our wow.exe patched version

**Comment by darkmord1991** [comment]
I did from the beginning.

**Comment by darkmord1991** [comment]
![image](https://cloud.githubusercontent.com/assets/811881/18890648/4e8b305e-8502-11e6-8333-082955d8ad71.png)




[worldserver.txt](https://github.com/JadeEmu/JadeCore_547/files/496575/worldserver.txt)
[authserver.txt](https://github.com/JadeEmu/JadeCore_547/files/496576/authserver.txt)

**Comment by Mysterium** [comment]
Are you using domain to login? Domains doesn't work..

**Comment by darkmord1991** [comment]
Oh, I  did not know that...
I will try it with IP

**Comment by darkmord1991** [comment]
Same Problem with IP.

**Comment by Mysterium** [comment]
Changed your config.wtf?

**Comment by darkmord1991** [comment]
SET locale "enUS"
SET installLocale "enUS"
SET realmlist "5.135.248.230:3725"
SET hwDetect "0"
SET videoOptionsVersion "5"
SET gxApi "D3D11"
SET gxWindow "0"
SET gxMaximize "0"
SET maxAnimThreads "6"
SET readTOS "1"
SET lastReadTOS "50407"
SET readEULA "1"
SET lastReadEULA "50407"
SET readTerminationWithoutNotice "1"
SET lastReadTerminationWithoutNotice "50407"
SET readScanning "1"
SET Sound_MusicVolume "0.40000000596046"
SET Sound_AmbienceVolume "0.60000002384186"
SET farclip "1000"
SET particleDensity "80"
SET waterDetail "2"
SET rippleDetail "1"
SET reflectionMode "0"
SET sunShafts "2"
SET groundEffectDensity "80"
SET groundEffectDist "200"
SET environmentDetail "125"
SET projectedTextures "1"
SET shadowMode "2"
SET shadowTextureSize "2048"
SET SSAO "1"
SET SSAOBlur "1"
SET textureFilteringMode "4"
SET terrainLodDist "500"
SET wmoLodDist "500"
SET componentTextureLevel "0"
SET realmName "Fury of Champions"
SET accountName "darkmord1991"

**Comment by darkmord1991** [comment]
I am using Port 3725, and its working. So no problem from that.

**Comment by cooler-SAI** [comment]
chack 127.0.0.1 for connections first

**Comment by darkmord1991** [comment]
Its running on a dedicated server, so I cant check local connection.

**Comment by cybrann** [comment]
I don't think it's good to post this here, ac-web.org or any other wow emulation forum would be better place to seek answer.
