### ISSUE TITLE
Malkorok issues

### ISSUE THREAD

**Issue by cybrann** [JadeEmu/JadeCore_547#15]
I have problem with Arcing Smash and Breath of Y'shaarj spells on Malkorok.
The problem with Arcing Smash is that it follows player when it is cast, so boss is spinning around instead of casting it to specified position.
The problem with Breath of Y'shaarj is that it should be cast of the position of the 3 previous Arcing Smashes but I got it to work with the one only not 3. I opened this issue so we can discuss this if anyone knows.

**Comment by cybrann** [comment]
Ah screw it I'll skip malkorok, I just can't figure out how to get this to work

**Comment by Keital** [comment]
hahaha bad guy malkorok!!

**Comment by cooler-SAI** [comment]
leave it open issue, may be someone can help

**Comment by a7244869** [comment]
So Maybe you can reference  3.3.5SunwellCore   IcecrownCitadel :boss_rotface.cpp 
https://github.com/callmephil/SunWellCore/blob/master/src/server/scripts/Northrend/IcecrownCitadel/boss_rotface.cpp
This BOSS   SPELL_SLIME_SPRAY      = 69508     Similar to the SPELL_ARCING_SMASH = 142815            
But it will not follows player cast  ,damage only the fan area do not move .
other 3.3.5code this spell damage will also be follows player  But this won't 
You can see this code Implementation method 
But I write malkorok according to his writing    is failed !

**Comment by cybrann** [comment]
Hmm well I think I made a fix for this, but we will see how it preforms.
