### ISSUE TITLE
SmartAI lost scripts

### ISSUE THREAD

**Issue by cooler-SAI** [JadeEmu/JadeCore_547#16]
In release JCDB547.03 we lost around 2300 SmartAI scripted entryes! It's huge number - don't forget to apply SmartAI Patch scripts BEFORE create Full DB release!

**Comment by Bodeguero** [comment]
@cooler-SAI you can update it and release to the community?

**Comment by cooler-SAI** [comment]
done  https://github.com/JadeEmu/JadeCore_547/releases so, I close it
