### ISSUE TITLE
Database Error giving Dump

### ISSUE THREAD

**Issue by Bodeguero** [JadeEmu/JadeCore_547#18]
I can not give Dump the new database - to which I released has no error over the new is to fix it?

Look error:

![database](https://cloud.githubusercontent.com/assets/8006687/18958342/591e846a-8630-11e6-9309-312180bbb719.jpg)

Gratfull

**Comment by Bodeguero** [comment]
summoning @cooler-SAI  for help )))

**Comment by phulo** [comment]
please put the rror file

**Comment by Bodeguero** [comment]
@phulo He stands/stop the creature table - you got to dump this file?

**Comment by Keital** [comment]
@Bodeguero try with CLI

**Comment by phulo** [comment]
dont use syslog use navicat

**Comment by phulo** [comment]
i dump JCDB_547_04_full_2016_09_28.sql db right now and got this
 [Msg] [Dtf] Finished - Successfully
all is ok

**Comment by Bodeguero** [comment]
@phulo You updated the database or is using the release of here?

**Comment by cooler-SAI** [comment]
@Bodeguero , try apply to your world before port full release

sql`
SET GLOBAL max_allowed_packet=64*1024*1024;
sql

**Comment by Bodeguero** [comment]
@cooler-SAI I did't understand what you want to say

**Comment by cooler-SAI** [comment]
create sql file, write:
SET GLOBAL max_allowed_packet=64*1024*1024;

then apply sql to your empty created world base, and import JCDB 04

**Comment by Bodeguero** [comment]
@cooler-SAI I'm sorry but I do not understand anything or in Navicat wants to dump, why I put as release of the dump and this not?

Already have about 15 minutes to not get out of it - what is the problem with your database release? The version I posted does not have that kind of mistake!
![cats](https://cloud.githubusercontent.com/assets/8006687/18964920/fc3d2c6a-8648-11e6-8dcb-f46eb6955acb.jpg)

**Comment by cooler-SAI** [comment]
use SQLyog

**Comment by Bodeguero** [comment]
@cooler-SAI I used SQLyog and does not pass the creature table :(

![database](https://cloud.githubusercontent.com/assets/8006687/18958342/591e846a-8630-11e6-9309-312180bbb719.jpg)

**Comment by cooler-SAI** [comment]
well, you must use my patch I think.
to SQLyog
```sql
SET GLOBAL max_allowed_packet=64*1024*1024;
```

**Comment by phulo** [comment]
your problem is not dumping the database is loading the database.

**Comment by Bodeguero** [comment]
@cooler-SAI What patch? Now not to understand anything! 🔨  do not know what is happening but i can not give Dump in your file - what was done in it? The strangest that I sent release of version 03 of Dump I know mistakes its not! I'm sorry you would most like to know what I'm doing wrong! Remembering that it is the first time this happens to me!

**Comment by phulo** [comment]
use console. Move to the sqlserver\bin directory

**Comment by cooler-SAI** [comment]
let's use TeamViewer

**Comment by phulo** [comment]
execute 
mysql.exe -u root -p

**Comment by Bodeguero** [comment]
@cooler-SAI go to Skype!

**Comment by phulo** [comment]
yes bodeguero your skype user???

**Comment by cooler-SAI** [comment]
loggin

**Comment by phulo** [comment]
cooler i add you to my skype and you dont accepted yet

**Comment by cooler-SAI** [comment]
@phulo , what's your nick?

**Comment by phulo** [comment]
yoandris2006

**Comment by cooler-SAI** [comment]
![scrin](https://cloud.githubusercontent.com/assets/812439/18965401/c12cae6a-8685-11e6-9482-c9be5d563184.jpg)

**Comment by cooler-SAI** [comment]
already Dumping - all good

**Comment by Bodeguero** [comment]
@cooler-SAI You will not answer me to Skype boss? You are exporting and regardless - I do not understand anything - is understanding what is my problem?

**Comment by alexkulya** [comment]
Conference on Skype, it's interesting. If anything, my skype: al.kulya
Конференция в скайпе, интересно. Если что, мой скайп: al.kulya

**Comment by cooler-SAI** [comment]
@Bodeguero join

**Comment by Bodeguero** [comment]
I do not know what's going on - why not let the simple database to give Dump? See my release has no errors!
https://github.com/JadeEmu/JadeCore_547/releases/tag/JCDB547.03
@cooler-SAI I'm in my work talking to you and you do not answer me boss!

**Comment by cooler-SAI** [comment]
@Bodeguero  you can log in Skype or not? I added you! I don't have any problems with Dump and Import

**Comment by cybrann** [comment]
@Bodeguero Have you tried HeidiSQL?

**Comment by Bodeguero** [comment]
@cybrann I do not use HeidiSQL - always leaves my bugadas databases for me to Dump I only use Navicat because I think better to work on it!

**Comment by cybrann** [comment]
@Bodeguero my skype is sko.du

**Comment by Bodeguero** [comment]
@cooler-SAI update release?

**Comment by cooler-SAI** [comment]
Release updated

**Comment by Bodeguero** [comment]
**Plus the size of the last release is smaller than the first so that correct?**

**Comment by cooler-SAI** [comment]
Fully correct

**Comment by Bodeguero** [comment]
Is not fixed'm the same mistake 
![cata](https://cloud.githubusercontent.com/assets/8006687/19009394/79d6af72-8741-11e6-8140-f8548ca05550.jpg)

**Comment by Bodeguero** [comment]
@Mysterium Thx for fix
