### ISSUE TITLE
Comunication

### ISSUE THREAD

**Issue by Keital** [JadeEmu/JadeCore_547#19]
Guys i think we need a way to comunicate apart from github, maybe a channel on rizon, dont have a problem adding you to facebok since i have connection to internet only at work and facebook lets me see messages if im not online when i log in

**Comment by phulo** [comment]
skype user?? keital u are latinamerican??

**Comment by Keital** [comment]
Caribean. I´m from Las Tunas. Cuba

**Comment by phulo** [comment]
holguin, Cuba here kb sere

**Comment by Cubansephiroth** [comment]
@Keital te agregue al facebook soy de Cuba igual. Necesito comentarte algo, acepta solicitud. kb @phulo

**Comment by Keital** [comment]
@phulo @Cubansephiroth agreguenme a face q es lo q mejor podemos usar aca

**Comment by Mysterium** [comment]
What is with discord?

**Comment by cooler-SAI** [comment]
arhh...Skype will be better, it's sad that not all can use it(

**Comment by Mysterium** [comment]
cooler, can you accept me in skype? xorewinz

**Comment by cybrann** [comment]
If someone needs my skype, here : sko.du
