### ISSUE TITLE
System Travis CI

### ISSUE THREAD

**Issue by Bodeguero** [JadeEmu/JadeCore_547#2]
**It will be integrated into the System Travis CI? It would be nice to have him to know the errors at compile time or generate the files.**

**Comment by cybrann** [comment]
It would be nice to have that. I agree.

**Comment by cooler-SAI** [comment]
accept!

**Comment by Bodeguero** [comment]
@cooler-SAI , you will make this integration? @cooler-SAI

**Comment by cooler-SAI** [comment]
no! leave it to you )))

**Comment by Bodeguero** [comment]
@cooler-SAI  only the Organization Administrator has access to it because it will allow direct access Travis CI with the Organization!

**Comment by cooler-SAI** [comment]
@Bodeguero , promoted

**Comment by Bodeguero** [comment]
@cooler-SAI thanks

**Comment by cybrann** [comment]
You will need to implement boost to in core for Travis CI to work I think

**Comment by Bodeguero** [comment]
@cybrann I have only one problem at the end of compilation channel.cpp file you can help me on this?

**Comment by cybrann** [comment]
Hmm there is solution. go to the player.cpp to the 22912 row and in the function 
`inline void Player::BuildPlayerChat(WorldPacket* data, uint8 msgtype, const std::string& text, uint32 language, const char* addonPrefix /*= NULL*/, const std::string& channel /*= ""*/) const`

Remove the prefix inline

**Comment by Bodeguero** [comment]
@cybrann thanks! Fixed Now!
