### ISSUE TITLE
Map for Error

### ISSUE THREAD

**Issue by Bodeguero** [JadeEmu/JadeCore_547#20]
Starting Battlefield System
Map file 'data/maps/0002226.map' is from an incompatible map version (MAPS v1.3), MAPS v1.4 is expected. Please recreate using the mapextractor.
Error loading map file: 
 data/maps/0002226.map

Map file 'data/maps/5712227.map' is from an incompatible map version (MAPS v1.3), MAPS v1.4 is expected. Please recreate using the mapextractor.
Error loading map file: 
 data/maps/5712227.map

VMapManager2: could not load 'data/vmaps/Wintergrasp_Tree_02.m2.vmo'
StaticMapTree::LoadMapTile() : could not acquire WorldModel pointer [22, 27]

**Comment by cybrann** [comment]
Check out some 5.4.8 repacks on ac-web, and download maps from there

**Comment by Bodeguero** [comment]
@cybrann I downloaded more than 05 repacks and all is version 1.3 where I find the version 1.4?

**Comment by wowharley** [comment]
I saw version 1.4 on junkybulgaria repo, i'll look for it and post you the link

**Comment by Bodeguero** [comment]
@wowharley I'm waiting . . .

**Comment by wowharley** [comment]
https://github.com/JunkyBulgaria/mop548/commit/adb9622c73fa3e86fc9f5db1afdf6f64bb4b58a0

**Comment by Keital** [comment]
We need the v1.4 maps

**Comment by Bodeguero** [comment]
https://github.com/JunkyBulgaria/mop548/blob/master/src/tools/map_extractor/System.cpp#L377

@wowharley You can extract it for me? I just need these 02 files if possible - another sure thing is that this version 4? 

For already used this extractor and is giving me the same error!

Grateful!

**Comment by wowharley** [comment]
Let me try and extract the maps for you

**Comment by wowharley** [comment]
I fork this repo, try the extractor on mine

**Comment by Bodeguero** [comment]
@wowharley You do not understand this - this map you will use is not for this source more we have the link in the repository description but to the project we are moving from 5.4.7 to 5.4.8.

Look:
https://github.com/JadeEmu/JadeCore_547/commit/6dfd88f4a59f4d5d5f1633e833795f810825c7f5

**Comment by wowharley** [comment]
i understand the project is moving to 5.4.8

i'm trying to find the patern to modify the core to extract v1.4 that your looking for.

Let me do more research and i will get back to you.

**Comment by Keital** [comment]
when i get at home maybe i revert some stuff, and hopefully this will get fixed

**Comment by Bodeguero** [comment]
@Keital I've been watching you made 05 changes without testing with Travis CI - is difficult to try to fix these errors - every time you change something send 1 commint at a time so we can see the errors.

Now is very complicated and difficult to fix/correct the Travis CI.

**Comment by Keital** [comment]
@Bodeguero Kay you´re right my bad. Lesson learned

**Comment by Bodeguero** [comment]
@Keital no problems  🔗

**Comment by Keital** [comment]
@Bodeguero im reverting all my shit xD

**Comment by wowharley** [comment]
Do you guys have a IRC channel going ?

**Comment by Bodeguero** [comment]
@wowharley We do not - more soon will!

**Comment by wowharley** [comment]
@Bodeguero excellent, i'm glad you guys are moving to 5.4.8. Can't wait to see the outcome of it and to help out 👍

**Comment by Bodeguero** [comment]
@wowharley You got the map v1.4?

**Comment by Bodeguero** [comment]
@Keital Did you get/have version 1.4?

**Comment by cybrann** [comment]
@Bodeguero Are you planning on using another core as base for 5.4.8?

**Comment by Bodeguero** [comment]
@cybrann I'm thinking of changing this to the 5.4.8 version, for that I need that map V 1.4 :neckbeard:

**Comment by Keital** [comment]
will discuss when mmaps are working, that's my first goal, then will see

**Comment by cybrann** [comment]
@Bodeguero Make a new branch here called 5.4.8 test, so I can check it out and try to fix maps problem.

**Comment by Bodeguero** [comment]
@cybrann Ok

**Comment by Keital** [comment]
i've created a branch for mmaps, use that for testing purposes related to that issue. also y need testers for the mmaps fixes i've pushed as i haven't downloaded the mmaps and all i'm doing is implementing and checking if build is correct, but i need someone to test ingame and give feedback.
