### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by Darkchas** [JadeEmu/JadeCore_547#21]
Is there some sort of Database tool like Truice? used to fix quite a few quests back in wotlk times and it was a handy tool. wondering if this core has something like that? If not sorry, just close this issue.

(tried to post on forums but cant)

**Comment by cooler-SAI** [comment]
I am using Truice and SAI editor

**Comment by Darkchas** [comment]
Cooler, could you post a download for your truice please if possible? i got the version 2.0 and v1.3.8.7 but the quest tab always errors.

Thank you for replying, you guys are really doing a great job.

**Comment by c0per0** [comment]
the db download link please? 
If not bother to ask here

**Comment by cooler-SAI** [comment]
https://mega.nz/#!eI0gVJJb!GRTaxfLqOJvskMl8wezthnO2YKGDqnz8nD3GHngtbnw
