### ISSUE TITLE
How set GM account?

### ISSUE THREAD

**Issue by hero2880** [JadeEmu/JadeCore_547#22]
I use ".account set gmlevel XXX 3 -1",in game ,".gm on"does not work...

**Comment by darkmord1991** [comment]
Same for me, Also setting the same in DB doesnt work.

**Comment by Bodeguero** [comment]
@hero2880 and @darkmord1991  In your database "auth" table has the "account" - it has the column `gmlevelo` put the level of GM you want to use!

Grateful!

**Comment by darkmord1991** [comment]
SO why there is a account_access table then?

**Comment by Bodeguero** [comment]
@darkmord1991 Yes to do in 02 is a new form of security to have the level and administrator access and game master!

**Comment by darkmord1991** [comment]
oh okay, you edited. I did not see that :)

**Comment by hero2880** [comment]
@darkmord1991 ,Is the problem solved? I still can not.

**Comment by darkmord1991** [comment]
It does working for me

**Comment by darkmord1991** [comment]
Use gmlevel 3 for both.

**Comment by hero2880** [comment]
I try again.

**Comment by hero2880** [comment]
God,I can not still.......!
"there are not the commmands"....

**Comment by Bodeguero** [comment]
@hero2880 have contact Via Skype? Send-me contact!

Gratfull

**Comment by hero2880** [comment]
@Bodeguero ,I haven't  Via Skype,i am Chinese.

**Comment by Bodeguero** [comment]
@hero2880 @darkmord1991 
First you do it:
![1](https://cloud.githubusercontent.com/assets/8006687/19040450/16d67c5a-8952-11e6-90bb-0f7d4f75b6ca.jpg)
Then do this:
![2](https://cloud.githubusercontent.com/assets/8006687/19040451/17033196-8952-11e6-9b92-03a45c0c7c54.jpg)

Now close the **authserver.exe** and **worldserver.exe** and on again!

It's working now?

**Comment by darkmord1991** [comment]
It worked for me, I just needed to login again. no restart required.

**Comment by hero2880** [comment]
@Bodeguero ,Thanks a lot! It is working now!
