### ISSUE TITLE
Vend-O-Tron D-Luxe does not work

### ISSUE THREAD

**Issue by darkmord1991** [JadeEmu/JadeCore_547#23]
Entry 24935
http://www.wowhead.com/npc=24935/vend-o-tron-d-luxe

No  Window opens and you can not buy anything.
Seen in Orgrimmar.

**Comment by alexkulya** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/7693165/19241527/ba36d9ec-8f17-11e6-9d87-8faba036b6a7.png)

It works fine. Next time, describes in detail the essence of the problem and apply a screenshot.

Closed.

Работает исправно. В следующий раз подробнее описывайте суть неисправности и прикладывайте скриншот.

Закрыто.
