### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by cooler-SAI** [JadeEmu/JadeCore_547#27]
Ok, we have crash
Rev: https://github.com/JadeEmu/JadeCore_547/commit/aeb4d9df2951e463fa3224ec75a22b725429a546

```sql
E:\Server\MoP\source\JadeCore_547\src\server\game\Conditions\DisableMgr.cpp:268 in DisableMgr::IsDisabledFor ASSERTION FAILED:
  type < MAX_DISABLE_TYPES
[0xa30997]
[0x4f9831]
[0x4f2f3a]
[0x4f2c34]
[0x4710de]
[0x30050d]
[0x333723]
[0x30bed2]
[0x30bb88]
[0x316093]
[0x315ea5]
[0x378c56]
[0x5435d9]
ACE_Task_Base::svc_run()+0x41 [0x8fcd1]
ACE_Thread_Adapter::invoke_i()+0x69 [0x90209]
ACE_Thread_Adapter::invoke()+0x71 [0x90181]
beginthreadex()+0x107 [0x24f7f]
endthreadex()+0x192 [0x25126]
BaseThreadInitThunk()+0x22 [0x13d2]
RtlUserThreadStart()+0x34 [0x15454]
```

**Comment by Bodeguero** [comment]
@cooler-SAI Compiling in debug mode and send us the error log!

Gratfull

**Comment by cybrann** [comment]
@cooler-SAI What is causing crash?

**Comment by cybrann** [comment]
By looking at it it's clear that assertion failed for disable tables, so I guess invalid entry in db is causing crash maybe, because the type is bigger than the allowed one.

**Comment by cooler-SAI** [comment]
looks like mmaps issue - I set mmaps off and server works, but console still have this errors
![fer](https://cloud.githubusercontent.com/assets/812439/19043011/062ab7d2-8997-11e6-986a-372966544d16.jpg)

**Comment by darkmord1991** [comment]
It happens if you try to use MMaps

**Comment by cooler-SAI** [comment]
since mmaps work in progress I close it
