### ISSUE TITLE
Some tables in auth and characters DB are not empty..

### ISSUE THREAD

**Issue by Cubansephiroth** [JadeEmu/JadeCore_547#28]
Some tables in auth Db and characters are not cleared. (sql/base)

auth.account_log_ip
auth.account_spell 
auth.realmcharacters

also several tables in charactes db have data too.

this is not really an issue but maybe they can be cleared to save some space and avoid a posible conflict with a character or account.

**Comment by cooler-SAI** [comment]
ok, we got it, It's not a bugreport - feel free to clearn it by yourself. In newt Milestone will clearn
