### ISSUE TITLE
Sludge Beast

### ISSUE THREAD

**Issue by darkmord1991** [JadeEmu/JadeCore_547#29]
http://www.wowhead.com/npc=52165/sludge-beast

http://www.wowhead.com/quest=29089/sludge-beast

Can not attack/kill that npc and its invisible.

**Comment by Mysterium** [comment]
All ok here.
http://imgur.com/a/vezql

**Comment by darkmord1991** [comment]
![image](https://cloud.githubusercontent.com/assets/811881/19092763/8204a45c-8a88-11e6-9966-2caeba11b292.png)

it appears and then it goes invisible

**Comment by darkmord1991** [comment]
![image](https://cloud.githubusercontent.com/assets/811881/19092783/9aed0b1c-8a88-11e6-9269-9f7ad53caa05.png)

**Comment by Mysterium** [comment]
Can't confirm this bug.
Resting place (gameobject) is working too
