### ISSUE TITLE
dear cooler-SAI  and your team!

### ISSUE THREAD

**Issue by cnmir2** [JadeEmu/JadeCore_547#3]
dear cooler-SAI  and your team! 
            i am newbie and i begin learn c++ from scratch  but i love wow .and respect all great work of your team !  i think i could test the bug in the game and report here  if you needed. :)  i want to join your team but i know i am not the master! but i want to do something to offer a little  hand ! 
             in any case  keep it up great jade team!!           
                                                                                                            ty yours

**Comment by cybrann** [comment]
As long as you do not do hackfixes and bad code you are welcome

**Comment by cooler-SAI** [comment]
Try fix simple DB bugs

**Comment by Keital** [comment]
as for simple db bugs and some spell fixing i can do my stuff, so if im welcome abord, happy to get an invite

**Comment by cooler-SAI** [comment]
@Keital  i invited you 2 weeks ago - you don't join, ready now?

**Comment by cnmir2** [comment]
me too happy to jioin your team :)

**Comment by cybrann** [comment]
@Keital spells do not need fixing they are pretty much almost fully fixed on classes. Only thing left to be done for some spells that cannot be sound in spell folder is give them proper fixes and remove hackfixes.

**Comment by cooler-SAI** [comment]
ok, If someone wanna join us - post new issue with request and show your skill ( Core fixer, DB, SAI scripts) I mean introduce yourself!
 and then, I close it
