### ISSUE TITLE
Mortal Coil and Agony Bugged.

### ISSUE THREAD

**Issue by Remix99** [JadeEmu/JadeCore_547#34]
* Mortal Coil: Its currently spammable can heal you instantly by just pressing the spells several times. The
 [Bugged Video] 
https://www.youtube.com/watch?v=kbQ999BUYao&feature=youtu.be
Should have a small Cooldown. The [Video how it should work]
https://www.youtube.com/watch?v=2SYicOwKki8

* Agony: Isn't working correctly. Not applying any dots on the target and is only hitting the person with "1" Damage. 
[Bugged Video]
https://www.youtube.com/watch?v=kbQ999BUYao&feature=youtu.be
Skip past 13 seconds.

Should apply a dot and should be stackable 10 times. More DMG also.
[Proof of Agony]
http://www.wowhead.com/spell=980/agony

**Comment by cybrann** [comment]
Agony is working perfectly for me.

**Comment by Remix99** [comment]
am I missing some spell sql update?

**Comment by Keital** [comment]
http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/
