### ISSUE TITLE
List of issues

### ISSUE THREAD

**Issue by DaisyPayne** [JadeEmu/JadeCore_547#35]
Hello, I have a list of a few issues of thing that don't work or sometime's do/don't work

I will list them off in section's. Big post I know, But this is what I have ran into so far I will keep updating as I keep playing. Amazing work so far.

Enchants 
Bloody Dancing Steel (Never proc's)
Spirit of conquest (Never Proc's)

--------------------------------------------

Item's 
Gong-Lu, Strength of Xuen (has the wrong proc animation)

Fen-Yu, Fury of Xuen (Has the wrong proc animation for Rogue's and Enhancement Shaman)

Black Blood of Y'Shaarj (Trinket proc's but does not stack)

Thok's Tail Tip (Proc's but does not provide the Mastery bouns also lower's haste rating)
https://i.imgur.com/RTuhl7G.jpg Trinket on. https://i.imgur.com/wi2D7Fx.jpg Trinket off.

Ticking Ebon Detonator (Proc's but gives low agility and does not decrement)

Skeer's Bloodsoaked Talisman (Proc's but does not stack from new proc's)

Evil Eye of Galakras (proc's but does not provide the cooldown recovery rate)

--------------------------------------------------

Classes 

Warrior 

Sudden Death ARMS (Proc's but sometimes does not reset Colossus Smash)

Charge (Sometimes only gives 15 rage instead of 20)

Warlock

Affliction Spec (Swapping to Affliction from any spec will not generate soul shards even with drain soul unless you relog.)

Destruction Spec (Swapping to Destruction from any spec will not generate Burning Ember's unless you relog.)

--------------------------------------------------

Movement 

Walking and standing still, spinning with A or D you spin very..very fast

Seeing someone else attack another player or creature, forces them to face the target when they themselfs are not looking. Make's it really hard for rogues to know if they're behind the target for Backstab.
screen shot's were taken from both points of views
https://i.imgur.com/mBtiiCy.jpg warrior that attacked the target
https://i.imgur.com/GeGnKIx.jpg warrior that was watching
notice how Somdk is facing the dummy, she's facing the last thing she had attacked
when on her point of view she was facing me

I would make a youtube vid of it. But I have no program to record. And bad upload speed.

-----------------------------------------------------

Creatures / mobs

Raider's Training Dummy are not immune to stuns when they should be

**Comment by Keital** [comment]
When submitting issues please make 1 post per issue, so its easier to close the thread, thanks for your.
http://www.trinitycore.org/f/topic/37-the-trinitycore-issuetracker-and-you/. 
Will close this
