### ISSUE TITLE
nazgrim BERSERKER STANCE

### ISSUE THREAD

**Issue by a7244869** [JadeEmu/JadeCore_547#4]
BOSS: nazgrim

Berserker stance(143594)  rage  not double acquire

Maybe can do some modification 

			void HandleOnHit()
			{
				if (InstanceScript* m_Instance = GetCaster()->GetInstanceScript())
					if (Creature * genNazgrim = m_Instance->instance->GetCreature(m_Instance->GetData64(eData::DATA_GENERAL_NAZGRIM)))
					{			
						if (genNazgrim->HasAura(143594))
						{ 
							AddRage(genNazgrim, 26, genNazgrim->GetGUID()); // On hit it gives 10 rage to nazgrim
						}
						else
						{
							AddRage(genNazgrim, 13, genNazgrim->GetGUID()); // On hit it gives 5 rage to nazgrim
						}
						if (Unit* target = GetHitUnit())
							if (AuraPtr sunderingBlow = target->GetAura(SPELL_SUNDERING_BLOW))
							{
								uint32 stacks = sunderingBlow->GetStackAmount();
								if (genNazgrim->HasAura(143594))
								{
								AddRage(genNazgrim, 26*stacks, genNazgrim->GetGUID()); // And for every stack of the debuff 10 more rage
								}
								else
								{
									AddRage(genNazgrim, 13 * stacks, genNazgrim->GetGUID()); // And for every stack of the debuff 5 more rage
								}
							}
					}
			}

This is only for SUNDERING_BLOW(143494) the modified 

There still needs to be solved AFTERSHOCK(143712)and RAVAGER(143872) hit player not acquire rage

KORKRON_BANNER_AURA	= 143536,   This spell Also have no acquire rage  effect

**Comment by cooler-SAI** [comment]
Summoning @cybrann )))

**Comment by cybrann** [comment]
I will do that, I never said boss is finished, and I also told you to not post new code here but in pull request.

**Comment by a7244869** [comment]
OK The next time will be in pull request
