### ISSUE TITLE
authserver running crash

### ISSUE THREAD

**Issue by hero2880** [JadeEmu/JadeCore_547#41]
logs:
JadeCore rev. stable-a5b72abffc7a+ 2016-10-08 23:11:17 +0200 (master branch) (Win64, Release) (authserver)
<Ctrl-C> to stop.

Using configuration file authserver.conf.
OpenSSL 1.0.2d 9 Jul 2015 (Library: OpenSSL 1.0.2d 9 Jul 2015)
Opening DatabasePool 'auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 5.5.9
MySQL server ver: 5.5.5-10.0.16-MariaDB 
[WARNING] MySQL client/server version mismatch; may conflict with behaviour of prepared statements.
Connected to MySQL database at 127.0.0.1
MySQL client library: 5.5.9
MySQL server ver: 5.5.5-10.0.16-MariaDB 
[WARNING] MySQL client/server version mismatch; may conflict with behaviour of prepared statements.
Connected to MySQL database at 127.0.0.1
DatabasePool 'auth' opened successfully. 2 total connections running.
Started auth database connection pool.
Updating Realm List...
No valid realms specified.

**Comment by cybrann** [comment]
Maybe you did not add realm in auth.realmlist database

**Comment by hero2880** [comment]
solved，thx.
