### ISSUE TITLE
Authserver not supporting other old versions?

### ISSUE THREAD

**Issue by Remix99** [JadeEmu/JadeCore_547#5]
With my 4.3.4 authserver I can connect to 3.3.5 realms
But If I want 5.4.7 , 4.3.4 and 3.3.5 all running on one authserver
Unable to connect to old versions with 5.4.7 authserver of jadecore
this is what I get (shown in screenshot below)
http://s21.postimg.org/6d6acvj2v/1474955617_74741193.png

**Comment by cooler-SAI** [comment]
only support 5.4.7 (18019)  at this time, so, closed
