### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by Keital** [JadeEmu/JadeCore_547#8]
Sorry for not accepting the invitation last week, was bussy teaching at University. 
Mi experience is fixing spell previously in ArkCore, now interesting in testing my skills implementing mmaps from TC into Jadecore also aiming at sniffing a good private mop server to spawn needed zones in jade, hints are apreciated, thanks for you time, keep up the good work

**Comment by cybrann** [comment]
https://github.com/JadeEmu/JadeCore_547/invitations
